title: "Соболь Екатерина. Лаборатория визуальной коммуникации"
header_title: "Лаборатория визуальной коммуникации"
email: katisobol@yandex.ru
author: Екатерина Соболь
description: "Соболь Екатерина. Лаборатория визуальной коммуникации"
baseurl: "/sobolstudio"
url: "https://katisobol.github.io/"
date_format: "%-d.%m.%Y"

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/ # будет URL вида /portfolio/ib-security/
  posts:
    output: true # это встроенная коллекция, можно оставить как есть
  products:
    output: true # на будущее

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio-case"
      extra_css:
        - /assets/css/page/portfolio-case.css # все файлы портфолио используют этот шаблон
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
